version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - '8080:8080'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass